const departments=[
 {id:'office',name:'Văn phòng',owner:'Trưởng Văn phòng',scope:'Tài chính · Nhân sự · Hành chính · Mua hàng · IT',functions:['Tài chính – kế toán','Nhân sự và hành chính','Mua hàng và nhà cung cấp','Quản trị hệ thống và dữ liệu'],processes:12,kpis:['Chi phí/Doanh thu','Tỷ lệ tuyển đúng hạn','SLA mua hàng','Độ đầy đủ dữ liệu'],risk:'Phân quyền thanh toán, đối soát và phê duyệt hai cấp'},
 {id:'ms',name:'Marketing & Sales',owner:'Head of Marketing & Sales',scope:'Website · Social · Ads · Lead · CRM · Sales · CSKH',functions:['Website, SEO và nội dung','Social Media và quảng cáo','Thu thập, phân loại và nuôi dưỡng lead','Pipeline bán hàng và chăm sóc khách hàng'],processes:18,kpis:['Lead đủ chuẩn','CPL/CAC','Tỷ lệ MQL → Booking','Doanh thu ảnh hưởng'],risk:'Đối soát nguồn lead, chống trùng và SLA phản hồi'},
 {id:'ops',name:'Vận hành',owner:'Head of Operations',scope:'3 chi nhánh · Bếp · Dịch vụ · Catering · QA',functions:['Vận hành ca và chi nhánh','Bếp, kho và chất lượng món','Dịch vụ khách hàng tại điểm bán','Catering và kiểm soát chất lượng'],processes:24,kpis:['Doanh thu/ca','Food cost','Thời gian phục vụ','Điểm hài lòng'],risk:'Checklist đầu/giữa/cuối ca và kiểm tra chéo chi nhánh'},
 {id:'tech',name:'Kỹ thuật',owner:'Trưởng Kỹ thuật',scope:'Bảo trì · Tài sản · Năng lượng · Sự cố',functions:['Bảo trì phòng ngừa','Xử lý yêu cầu và sự cố','Quản lý tài sản thiết bị','Theo dõi điện, nước và năng lượng'],processes:11,kpis:['Uptime thiết bị','MTTR','Tỷ lệ bảo trì đúng hạn','Chi phí năng lượng'],risk:'Lịch bảo trì, nhật ký thiết bị và phê duyệt nghiệm thu'},
 {id:'security',name:'Bảo vệ & HSE',owner:'Trưởng An ninh & HSE',scope:'An ninh · PCCC · An toàn · Sự cố · Tuân thủ',functions:['Kiểm soát ra vào','Tuần tra và bàn giao ca','PCCC và ứng phó khẩn cấp','An toàn lao động và báo cáo sự cố'],processes:10,kpis:['Sự cố an ninh','Tỷ lệ tuần tra đủ','Thời gian phản ứng','Tỷ lệ đào tạo an toàn'],risk:'Nhật ký ca, bằng chứng hình ảnh và phân cấp sự cố'}
];
const navTitles={overview:'Tổng quan điều hành',organization:'Cơ cấu quản trị 5 bộ phận',updates:'Cập nhật dữ liệu phòng ban',process:'Quy trình & công việc',crm:'Marketing & Sales',kpi:'KPI & báo cáo',data:'Dữ liệu & tích hợp'};
const content=document.querySelector('#content');
const updateKey='laHayeDepartmentUpdatesV1';
const seedUpdates=[
 {id:'UP-1001',department:'Vận hành',period:'2026-07-18',category:'KPI vận hành',title:'Doanh thu ca tối',value:'428',unit:'triệu đồng',owner:'Quản lý CN1',status:'approved',note:'Đã đối soát với POS',updatedAt:'18/07 12:30'},
 {id:'UP-1002',department:'Marketing & Sales',period:'2026-07-18',category:'Lead & CRM',title:'Lead đủ chuẩn trong ngày',value:'47',unit:'lead',owner:'Quang Huy',status:'submitted',note:'Nguồn Meta, Google và Website',updatedAt:'18/07 11:45'},
 {id:'UP-1003',department:'Kỹ thuật',period:'2026-07-18',category:'Bảo trì & sự cố',title:'Thiết bị cần xử lý',value:'3',unit:'thiết bị',owner:'Trưởng Kỹ thuật',status:'changes',note:'Thiếu ảnh nghiệm thu tủ đông CN2',updatedAt:'18/07 10:20'},
 {id:'UP-1004',department:'Văn phòng',period:'2026-07-17',category:'Tài chính & mua hàng',title:'Chi phí mua hàng trong ngày',value:'186',unit:'triệu đồng',owner:'Kế toán tổng hợp',status:'draft',note:'Đang chờ hóa đơn từ 2 nhà cung cấp',updatedAt:'17/07 17:10'},
 {id:'UP-1005',department:'Bảo vệ & HSE',period:'2026-07-18',category:'An ninh & an toàn',title:'Tỷ lệ tuần tra đủ điểm',value:'100',unit:'%',owner:'Ca trưởng bảo vệ',status:'approved',note:'Đủ 3 chi nhánh',updatedAt:'18/07 09:05'}
];
let updateRecords=loadUpdates();
let updateFilters={department:'Tất cả',status:'Tất cả',query:''};
const views={
 overview:()=>`<div class="notice"><div><b>Hiệu suất toàn công ty đang được hợp nhất</b><small>5 bộ phận · 3 chi nhánh · 75 quy trình chuẩn · dữ liệu minh họa</small></div><button data-go="organization">Xem cơ cấu →</button></div><div class="kpis">${[['Doanh thu tháng','12,8 tỷ','↑ 15,7%'],['Lead đủ chuẩn','1.250','↑ 12,5%'],['Việc đúng hạn','87,4%','↑ 4,2 điểm'],['Khách quay lại','32,4%','↑ 6,1 điểm']].map((x,i)=>kpi(x,i)).join('')}</div><div class="two"><section class="panel"><div class="panel-head"><div><h3>Sales pipeline</h3><small>Giá trị quy đổi 4,8 tỷ</small></div></div><div class="funnel">${[['Lead',428,100],['MQL',226,72],['SQL',132,52],['Cơ hội',74,36],['Booking',42,24],['Hoàn tất',35,18]].map(x=>`<div><div><span>${x[0]}</span><b>${x[1]}</b></div><i style="width:${x[2]}%"></i></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><h3>Công việc trọng tâm</h3><small>4 việc đang mở</small></div></div><div class="tasks">${task('Hoàn thiện landing page Catering','Minh Anh · hạn 20/07','Đang làm','')}${task('Duyệt lịch nội dung tuần 30','Thu Hà · hạn hôm nay','Chờ duyệt','amber')}${task('Đối soát lead Meta với CRM','Quang Huy · hạn 21/07','Cần làm','')}${task('Báo cáo pipeline catering','Anh Tuấn · hạn 25/07','Hoàn tất','green')}</div></section></div>`,
 organization:()=>`<div class="page-intro"><div><h2>Cấu trúc quản trị thống nhất</h2><p>Mỗi chức năng có một chủ sở hữu, đầu vào, đầu ra, KPI và cơ chế báo cáo.</p></div><button class="primary" data-toast="Đã mở biểu mẫu đề xuất đơn vị mới">+ Thêm đơn vị</button></div><section class="org"><div class="leadership">BAN LÃNH ĐẠO<small>Chiến lược · Phê duyệt · Kiểm soát</small></div><div class="org-line"></div><div class="governance"><b>KHUNG QUẢN TRỊ CHUNG</b><span>Mục tiêu</span><span>Chủ sở hữu</span><span>Quy trình</span><span>KPI</span><span>Dữ liệu</span></div><div class="departments">${departments.map(d=>`<article class="department" data-dept="${d.id}"><h3>${d.name}</h3><b>${d.owner}</b><p>${d.scope}</p><small>4 chức năng</small><small>${d.processes} quy trình</small><button>Xem hồ sơ bộ phận →</button></article>`).join('')}</div><div class="collab">PHỐI HỢP XUYÊN BỘ PHẬN · RACI · SLA · DỮ LIỆU CHUNG</div></section>`,
 process:()=>`<div class="page-intro"><div><h2>Bảng công việc liên phòng ban</h2><p>Nhấn vào thẻ để mô phỏng chuyển trạng thái và ghi nhận lịch sử.</p></div><button class="primary" data-toast="Đã tạo bản nháp công việc mới">+ Tạo công việc</button></div><div class="kanban">${[['Cần làm',['Đối soát lead Meta','Kiểm kê tài sản CN2']],['Đang làm',['Landing page Catering','Bảo trì tủ đông']],['Chờ duyệt',['Lịch nội dung tuần 30','Định mức nguyên liệu']],['Hoàn tất',['Checklist PCCC','Báo cáo doanh thu tuần']]].map((c,ci)=>`<section class="column"><header>${c[0]}<b>${c[1].length}</b></header>${c[1].map((t,i)=>`<article class="card" data-cycle><small>${['M&S','Kỹ thuật','Vận hành'][i%3]} · Ưu tiên ${i?'vừa':'cao'}</small><b>${t}</b><span>${['Minh Anh','Quang Huy','Lan Chi'][i%3]} · hạn ${20+i}/07</span></article>`).join('')}</section>`).join('')}</div>`,
 crm:()=>`<div class="page-intro"><div><h2>Marketing & Sales Command Center</h2><p>Website, social, quảng cáo, lead, CRM và doanh thu trên một luồng dữ liệu.</p></div><button class="primary" data-toast="Đã tạo bản nháp chiến dịch">+ Tạo chiến dịch</button></div><div class="channels">${[['Website & SEO','12.480 phiên','88'],['Content & Social','2,1M tiếp cận','76'],['Meta Ads','620 lead','82'],['Google Ads','311 lead','91'],['Google Maps','4,6 điểm','79']].map(x=>`<article class="channel"><h3>${x[0]}</h3><p>Hiệu suất tháng</p><strong>${x[1]}</strong><div class="progress"><i style="width:${x[2]}%"></i></div><small>${x[2]}% so với mục tiêu</small></article>`).join('')}</div><section class="panel"><div class="panel-head"><div><h3>Pipeline khách hàng</h3><small>Nguồn CRM · dữ liệu minh họa</small></div></div><table><thead><tr><th>Khách hàng</th><th>Nguồn</th><th>Phạm vi</th><th>Giá trị</th><th>Giai đoạn</th><th>Phụ trách</th></tr></thead><tbody>${[['Công ty An Phú','Website','Catering','85 triệu','Cơ hội','Anh Tuấn'],['Nguyễn Ngọc Hà','Facebook','CN1','12 triệu','SQL','Quang Huy'],['Công ty GreenLab','Giới thiệu','Catering','145 triệu','Booking','Anh Tuấn'],['Trần Khánh Linh','TikTok','CN2','8 triệu','MQL','Lan Chi']].map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`,
 kpi:()=>`<div class="page-intro"><div><h2>Thẻ điểm điều hành</h2><p>KPI được phân tầng theo công ty, bộ phận, chi nhánh và vị trí.</p></div><button class="primary" data-toast="Đã tạo lịch gửi báo cáo tháng">Lập lịch báo cáo</button></div><div class="kpis">${[['Doanh thu/Chi nhánh','4,27 tỷ','Đạt 106%'],['Food cost','31,2%','Trong ngưỡng'],['SLA phản hồi lead','92,8%','Tăng 5,4 điểm'],['Uptime thiết bị','98,6%','Đạt mục tiêu']].map((x,i)=>kpi(x,i)).join('')}</div><section class="panel"><div class="panel-head"><div><h3>Ma trận KPI mẫu</h3><small>Chủ sở hữu · nguồn dữ liệu · tần suất</small></div></div><table><thead><tr><th>KPI</th><th>Chủ sở hữu</th><th>Nguồn</th><th>Mục tiêu</th><th>Tần suất</th><th>Trạng thái</th></tr></thead><tbody>${[['Doanh thu thuần','Head Operations','POS/ERP','≥ 12 tỷ','Ngày/Tháng','Đạt'],['Tỷ lệ MQL → Booking','Head M&S','CRM','≥ 18%','Tuần','Đạt'],['Food cost','Bếp trưởng + Finance','POS/Kho','≤ 32%','Tuần','Đạt'],['MTTR kỹ thuật','Trưởng Kỹ thuật','Helpdesk','≤ 4 giờ','Tuần','Cảnh báo'],['Tuần tra đủ điểm','Trưởng Bảo vệ','Checklist','100%','Ngày','Đạt']].map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`,
 data:()=>`<div class="page-intro"><div><h2>Trung tâm dữ liệu & tích hợp</h2><p>Mỗi nguồn dữ liệu có chủ sở hữu, định nghĩa và lịch đồng bộ.</p></div><button class="primary" data-toast="Đã mở trình kết nối nguồn dữ liệu">+ Kết nối nguồn</button></div><div class="health">${[['7/9','Nguồn đang đồng bộ'],['96,8%','Bản ghi hợp lệ'],['2 phút','Độ trễ CRM'],['3','Cảnh báo cần xử lý']].map(x=>`<article><strong>${x[0]}</strong><span>${x[1]}</span></article>`).join('')}</div><section class="panel"><div class="panel-head"><div><h3>Danh mục nguồn dữ liệu</h3><small>Không phụ thuộc một phần mềm cụ thể</small></div></div><table><thead><tr><th>Nguồn</th><th>Dữ liệu</th><th>Chủ sở hữu</th><th>Đồng bộ</th><th>Chất lượng</th></tr></thead><tbody>${[['POS','Doanh thu · hóa đơn','Vận hành + Finance','15 phút','99,2%'],['CRM','Lead · pipeline · hoạt động','Marketing & Sales','2 phút','97,1%'],['Meta/Google','Chi phí · click · conversion','Marketing','60 phút','94,6%'],['Kho/Mua hàng','Nhập · xuất · tồn','Văn phòng + Bếp','30 phút','96,3%'],['Helpdesk','Sự cố · tài sản · SLA','Kỹ thuật','5 phút','98,4%']].map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></section><div class="architecture"><div><b>01</b>Nguồn dữ liệu</div><div><b>02</b>Tích hợp/API</div><div><b>03</b>Kho dữ liệu chung</div><div><b>04</b>Định nghĩa KPI</div><div><b>05</b>Dashboard & cảnh báo</div></div>`
};
views.updates=()=>{
 const visible=filteredUpdates();
 const submitted=updateRecords.filter(x=>x.status==='submitted').length;
 const approved=updateRecords.filter(x=>x.status==='approved').length;
 const changes=updateRecords.filter(x=>x.status==='changes').length;
 return `<div class="page-intro"><div><h2>Cập nhật dữ liệu phòng ban</h2><p>Nhập, gửi duyệt và theo dõi dữ liệu vận hành theo một cấu trúc thống nhất.</p></div><span class="demo-badge">Lưu trên trình duyệt này</span></div>
 <div class="update-summary"><article><strong>${updateRecords.length}</strong><span>Tổng bản ghi</span></article><article><strong>${submitted}</strong><span>Chờ phê duyệt</span></article><article><strong>${approved}</strong><span>Đã phê duyệt</span></article><article><strong>${changes}</strong><span>Cần bổ sung</span></article></div>
 <div class="update-layout"><section class="panel"><div class="panel-head"><div><h3>Thêm bản cập nhật</h3><small>Áp dụng chung cho 5 phòng ban</small></div></div><form class="entry-form" id="updateForm">
 <label class="wide">Phòng ban<select name="department" required>${departments.map(d=>`<option>${d.name}</option>`).join('')}</select></label>
 <label>Ngày dữ liệu<input name="period" type="date" value="${new Date().toISOString().slice(0,10)}" required></label>
 <label>Nhóm dữ liệu<select name="category"><option>KPI vận hành</option><option>Tài chính & mua hàng</option><option>Lead & CRM</option><option>Bảo trì & sự cố</option><option>An ninh & an toàn</option><option>Nhân sự</option></select></label>
 <label class="wide">Tên chỉ tiêu / nội dung<input name="title" placeholder="Ví dụ: Doanh thu ca tối" required></label>
 <label>Giá trị<input name="value" placeholder="428" required></label><label>Đơn vị<input name="unit" placeholder="triệu đồng" required></label>
 <label class="wide">Người phụ trách<input name="owner" placeholder="Họ tên hoặc vị trí" required></label>
 <label class="wide">Ghi chú / bằng chứng<textarea name="note" placeholder="Nguồn dữ liệu, nguyên nhân chênh lệch, liên kết tài liệu..."></textarea></label>
 <div class="form-hint">Bản ghi mới ở trạng thái Nháp. Người cập nhật phải gửi duyệt; trưởng bộ phận hoặc Ban lãnh đạo mới phê duyệt.</div>
 <button class="primary" type="submit">Lưu bản nháp</button></form></section>
 <section class="panel"><div class="panel-head"><div><h3>Danh sách cập nhật</h3><small>${visible.length} bản ghi theo bộ lọc</small></div></div><div class="record-toolbar"><input id="recordQuery" value="${escapeHtml(updateFilters.query)}" placeholder="Tìm nội dung hoặc người phụ trách"><select id="departmentFilter"><option>Tất cả</option>${departments.map(d=>`<option ${updateFilters.department===d.name?'selected':''}>${d.name}</option>`).join('')}</select><button class="primary" id="exportRecords">Xuất CSV</button></div><div class="record-list">${renderUpdateRows(visible)}</div></section></div>
 <div class="two" style="margin-top:18px"><section class="panel"><div class="panel-head"><div><h3>Luồng phê duyệt chuẩn</h3><small>Nháp → Gửi duyệt → Phê duyệt / Yêu cầu bổ sung</small></div></div><div class="architecture"><div><b>01</b>Nhân viên nhập</div><div><b>02</b>Trưởng bộ phận kiểm tra</div><div><b>03</b>Dữ liệu được khóa</div><div><b>04</b>Dashboard cập nhật</div></div></section><section class="panel"><div class="panel-head"><div><h3>Hoạt động gần đây</h3><small>Nhật ký trên thiết bị</small></div></div><div class="activity">${updateRecords.slice(0,4).map(x=>`<div><time>${x.updatedAt}</time><p><b>${x.owner}</b><span>${statusLabel(x.status)} · ${x.title}</span></p></div>`).join('')}</div></section></div>`;
};
function loadUpdates(){try{const stored=localStorage.getItem(updateKey);return stored?JSON.parse(stored):seedUpdates}catch{return seedUpdates}}
function saveUpdates(){localStorage.setItem(updateKey,JSON.stringify(updateRecords))}
function filteredUpdates(){return updateRecords.filter(x=>(updateFilters.department==='Tất cả'||x.department===updateFilters.department)&&(updateFilters.status==='Tất cả'||x.status===updateFilters.status)&&(`${x.title} ${x.owner} ${x.category}`.toLowerCase().includes(updateFilters.query.toLowerCase())))}
function statusLabel(s){return {draft:'Nháp',submitted:'Chờ duyệt',approved:'Đã duyệt',changes:'Cần bổ sung'}[s]||s}
function renderUpdateRows(rows){if(!rows.length)return '<div class="empty-state">Không có bản ghi phù hợp.</div>';return `<table><thead><tr><th>Nội dung</th><th>Phòng ban</th><th>Giá trị</th><th>Phụ trách</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${rows.map(x=>`<tr><td><span class="record-title">${escapeHtml(x.title)}</span><small class="record-meta">${x.category} · ${x.period}</small></td><td>${x.department}</td><td><b>${escapeHtml(x.value)}</b> ${escapeHtml(x.unit)}</td><td>${escapeHtml(x.owner)}</td><td><span class="status ${x.status}">${statusLabel(x.status)}</span></td><td><div class="row-actions"><button data-record="${x.id}" data-record-action="view">Xem</button>${x.status==='draft'||x.status==='changes'?`<button data-record="${x.id}" data-record-action="submit">Gửi duyệt</button>`:''}${x.status==='submitted'?`<button data-record="${x.id}" data-record-action="approve">Duyệt</button><button data-record="${x.id}" data-record-action="changes">Bổ sung</button>`:''}</div></td></tr>`).join('')}</tbody></table>`}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function bindUpdates(){const form=document.querySelector('#updateForm');if(!form)return;form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);const now=new Date();updateRecords.unshift({id:`UP-${Date.now()}`,department:String(f.get('department')),period:String(f.get('period')),category:String(f.get('category')),title:String(f.get('title')),value:String(f.get('value')),unit:String(f.get('unit')),owner:String(f.get('owner')),status:'draft',note:String(f.get('note')||''),updatedAt:now.toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})});saveUpdates();show('updates');toast('Đã lưu bản nháp trên trình duyệt')};document.querySelector('#recordQuery').oninput=e=>{updateFilters.query=e.target.value;refreshUpdateList()};document.querySelector('#departmentFilter').onchange=e=>{updateFilters.department=e.target.value;show('updates')};document.querySelector('#exportRecords').onclick=exportRecords;document.querySelectorAll('[data-record-action]').forEach(b=>b.onclick=()=>recordAction(b.dataset.record,b.dataset.recordAction))}
function refreshUpdateList(){document.querySelector('.record-list').innerHTML=renderUpdateRows(filteredUpdates());document.querySelectorAll('[data-record-action]').forEach(b=>b.onclick=()=>recordAction(b.dataset.record,b.dataset.recordAction))}
function recordAction(id,action){const record=updateRecords.find(x=>x.id===id);if(!record)return;if(action==='view'){document.querySelector('#drawerContent').innerHTML=`<p class="owner">BẢN CẬP NHẬT ${record.id}</p><h2>${escapeHtml(record.title)}</h2><p class="owner">${record.department} · ${record.period}</p><h4>Giá trị</h4><div class="drawer-grid"><div><b>${escapeHtml(record.value)}</b><small>${escapeHtml(record.unit)}</small></div><div><b>${statusLabel(record.status)}</b><small>Trạng thái</small></div></div><h4>Người phụ trách</h4><p>${escapeHtml(record.owner)}</p><h4>Ghi chú / bằng chứng</h4><p>${escapeHtml(record.note||'Chưa có ghi chú')}</p>`;document.querySelector('#drawer').classList.add('open');document.querySelector('#drawerBackdrop').classList.add('open');return}record.status={submit:'submitted',approve:'approved',changes:'changes'}[action]||record.status;record.updatedAt=new Date().toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});saveUpdates();show('updates');toast(action==='approve'?'Đã phê duyệt và khóa bản ghi':action==='changes'?'Đã yêu cầu bổ sung':'Đã gửi trưởng bộ phận duyệt')}
function exportRecords(){const headers=['ID','Phòng ban','Ngày','Nhóm dữ liệu','Nội dung','Giá trị','Đơn vị','Người phụ trách','Trạng thái','Ghi chú'];const lines=[headers,...updateRecords.map(x=>[x.id,x.department,x.period,x.category,x.title,x.value,x.unit,x.owner,statusLabel(x.status),x.note])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='la-haye-cap-nhat-phong-ban.csv';a.click();URL.revokeObjectURL(a.href);toast('Đã xuất dữ liệu CSV')}
function kpi(x,i){const heights=[[25,38,34,52,48,66,73],[32,28,45,38,61,58,76],[20,30,25,42,55,51,69],[28,36,31,48,44,60,72]][i%4];return `<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small><div class="bars">${heights.map(h=>`<i style="height:${h}%"></i>`).join('')}</div></article>`}
function task(title,meta,status,color){return `<div class="task"><i class="dot ${color}"></i><div><b>${title}</b><small>${meta}</small></div><span class="pill">${status}</span></div>`}
function show(view){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#pageTitle').textContent=navTitles[view];content.innerHTML=views[view]();bind();window.scrollTo({top:0,behavior:'smooth'});document.querySelector('#sidebar').classList.remove('open')}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));document.querySelectorAll('[data-dept]').forEach(b=>b.onclick=()=>openDept(b.dataset.dept));document.querySelectorAll('[data-cycle]').forEach(c=>c.onclick=()=>{c.style.opacity='.45';toast('Đã chuyển trạng thái và ghi lịch sử thay đổi')});bindUpdates()}
function openDept(id){const d=departments.find(x=>x.id===id);document.querySelector('#drawerContent').innerHTML=`<p class="owner">HỒ SƠ BỘ PHẬN</p><h2>${d.name}</h2><p class="owner">Chịu trách nhiệm chính: <b>${d.owner}</b></p><h4>Phạm vi</h4><p>${d.scope}</p><h4>Chức năng chính</h4><ul>${d.functions.map(x=>`<li>${x}</li>`).join('')}</ul><h4>KPI điều hành</h4><div class="drawer-grid">${d.kpis.map((x,i)=>`<div><b>${[92,87,96,89][i]}%</b><small>${x}</small></div>`).join('')}</div><h4>Kiểm soát trọng yếu</h4><p>${d.risk}</p><h4>Quy mô chuẩn hóa</h4><div class="drawer-grid"><div><b>${d.processes}</b><small>Quy trình</small></div><div><b>4</b><small>Chức năng</small></div></div>`;document.querySelector('#drawer').classList.add('open');document.querySelector('#drawerBackdrop').classList.add('open')}
function closeDrawer(){document.querySelector('#drawer').classList.remove('open');document.querySelector('#drawerBackdrop').classList.remove('open')}
function toast(msg){const t=document.querySelector('#toast');t.textContent='✓ '+msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#menu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#closeDrawer').onclick=closeDrawer;document.querySelector('#drawerBackdrop').onclick=closeDrawer;document.querySelector('#scope').onchange=e=>toast('Đã chuyển phạm vi: '+e.target.value);show('overview');
